name: presentation_card
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
  - family: Pacifico
    fonts:
      - asset: fonts/pacifico/Pacifico-Regular.ttf
  - family: Roboto
    fonts:
      - asset: fonts/roboto/Roboto-Black.ttf
        weight: 900
      - asset: fonts/roboto/Roboto-BlackItalic.ttf
        weight: 900
        style: italic
      - asset: fonts/roboto/Roboto-Bold.ttf
        weight: 700
      - asset: fonts/roboto/Roboto-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: fonts/roboto/Roboto-Medium.ttf
        weight: 500
      - asset: fonts/roboto/Roboto-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: fonts/roboto/Roboto-Regular.ttf
        weight: 400
      - asset: fonts/roboto/Roboto-Italic.ttf
        weight: 400
        style: italic
      - asset: fonts/roboto/Roboto-Light.ttf
        weight: 300
      - asset: fonts/roboto/Roboto-LightItalic.ttf
        weight: 300
        style: italic
      - asset: fonts/roboto/Roboto-Thin.ttf
        weight: 100
      - asset: fonts/roboto/Roboto-ThinItalic.ttf
        weight: 100
        style: italic
